name: drupaltraining
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
nfs_mount_enabled: true

hooks:
  post-start:
    - composer: install
    - exec: /var/www/html/db/import-db.sh
    - exec: drush updb -y
    - exec: drush cim -y
    - exec-host: cp web/sites/example.development.services.yml web/sites/development.services.yml
    - exec-host: mkdir -p web/sites/default/files/images
    - exec-host: chmod -R ugo+w web/sites/default/files/images/
    - exec-host: cp -rf web/assets/images/* web/sites/default/files/images/
    - exec: drush cr
    - exec-host: ddev launch /user
